version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3000
    entrypoint:  ./entrypoint.sh
    volumes:
      - ./backend:/home/node/backend
    depends_on:
      - db

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/home/node/frontend
  #   depends_on:
  #     - db  

  db:
    container_name: db
    build: .
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tubaplay_resales
      - MYSQL_ROOT_PASSWORD=root
